print('Welcome to the Quiz Show')
print('Do you want to Play? type in "yes" or "no"')
playInput = input()
if playInput != 'yes':
    quit()

def check_guess(guess, answer):
    global score
    still_guessing = True
    attempts = 0
    while still_guessing and attempts < 3:
        if guess.lower() == answer.lower():
            print('Correct Answer')
            score += 1
            still_guessing = False
        elif attempts < 2:
            guess = input('Wrong Answer! Try again ')
        attempts += 1
    if attempts == 3:
        print('You Lost, better luck next time!')
        print('You got', score, 'Questions correct!')
        quit()

score = 0
guess1 = input('Which animal is known as the "Ship of the Desert"? ')
check_guess(guess1, 'Camel')
guess2 = input('How many days are there in a week? ')
check_guess(guess2, '7')
guess3 = input('How many hours are there in a day? ')
check_guess(guess3, '24')
guess4 = input('How many letters are there in the English alphabet? ')
check_guess(guess4, '26')
guess5 = input('Rainbow consists of how many colours? ')
check_guess(guess5, '7')
guess6 = input('How many days are there in a year? ')
check_guess(guess6, '365')
guess7 = input('How many minutes are there in an hour? ')
check_guess(guess7, '60')
guess8 = input('How many seconds make one hour? ')
check_guess(guess8, '3600')
guess9 = input('How many legs do insects have? ')
check_guess(guess9, '6')
guess10 = input('How many vowels are there in the alphabet? ')
check_guess(guess10, '5')
guess11 = input('Which animal is known as the King or the Jungle? ')
check_guess(guess11, 'lion')
guess12 = input('Name the biggest continent in the world ')
check_guess(guess12, 'asia')
guess13 = input('How many continents are there in the world? ')
check_guess(guess13, '7')
guess14 = input('Which is the smallest month of the year? ')
check_guess(guess14, 'february')
guess15 = input('Name the house made of Ice ')
check_guess(guess15, 'igloo')
guess16 = input('Which color symbolises peace ')
check_guess(guess16, 'white')
guess17 = input('Sun rises in the... ? ')
check_guess(guess17, 'east')
guess18 = input('How many sites are there in a triangle? ')
check_guess(guess18, '3')
guess19 = input('Name the largest planet of our Solar System ')
check_guess(guess19, 'jupiter')
guess20 = input('How many years are there in one Millenium? ')
check_guess(guess20, '1000')
guess21 = input('Name the first man to walk on the Moon ')
check_guess(guess21, 'neil armstrong')
guess22 = input('Name the longest river on the Earth ')
check_guess(guess22, 'Nile')
guess23 = input('Name the smallest Continent ')
check_guess(guess23, 'Australia')
guess24 = input('Which is the principal source of energy for the Earth? ')
check_guess(guess24, 'sun')
guess25 = input('Anti-clockwise is it from left or right? ')
check_guess(guess25, 'left')
guess26 = input('Name the planet nearest to the Earth ')
check_guess(guess26, 'mercury')
guess27 = input('Name a bird that lays the largest eggs ')
check_guess(guess27, 'ostrich')
guess28 = input('Which is the tallest mountian in the world? ')
check_guess(guess28, 'mount everest')
guess29 = input('Who invented electricity? ')
check_guess(guess29, 'benjamin franklin')
guess30 = input('Which continent is known as the "Dark" continent? ')
check_guess(guess30, 'africa')
guess31 = input('Name the planet known as the Red Planet? ')
check_guess(guess31, 'mars')
guess32 = input('How many millimeters are there in a centimeter? ')
check_guess(guess32, '10')
guess33 = input('Name the hardest substance available on Earth ')
check_guess(guess33, 'diamond')
guess34 = input('Name the largest ocean in the World? ')
check_guess(guess34, 'pacific ocean')
guess35 = input('Which is the smallest ocean in the World? (a)Indian, (b)Pacific, (c)Atlantic or (d)Arctic. Type in a, b, c or d ')
check_guess(guess35, 'd')
guess36 = input('Which country gifted the "Statue of Liberty" to the USA in 1886? (a)France, (b)Canada, (c)Brazil or (d)England. Type in a, b, c or d ')
check_guess(guess36, 'a')
guess37 = input('Which country is also known as the "Land of Rising Sun"? (a)Japan, (b)New Zealand, (c)Fiji or (d)China. ')
check_guess(guess37, 'a')
guess38 = input('Which one is the largest tropical rain forest in the world? ')
check_guess(guess38, 'amazon')
guess39 = input('What is the boiling point temperature (water)? (a)50, (b)100, (c)150 or (d)200 ')
check_guess(guess39, 'b')
guess40 = input('In Greek mythology, what was the name of the three headed dog that guarded the gate to the underworld? ')
check_guess(guess40, 'cerberus')